### ISSUE TITLE
[Feature] Cata shared dr-categories (deep freeze + ring of frost)

### ISSUE THREAD

**Issue by XiconQoo** [wardz/DRList-1.0#19]
As you mentioned in https://github.com/wardz/DRList-1.0/blob/master/DRList-1.0/Spells.lua#L828 already, a spell having two categories is something DRList cannot handle right now.

My suggesetion is sth like this:

```lua
function Lib:GetCategoryBySpellID(spellID)
    if Lib.gameExpansion == "classic" then
        -- OBSOLETE: second return value is no longer needed after Classic Era patch 1.15.0.
        local category = Lib.spellList[spellID]
        if not category then return end
        return category, spellID
    end

    local category = Lib.spellList[spellID]
    if type(category) == "table" then
        return unpack(category)
    else
        return category
    end
end
```

This would initially not break addons using DRList, considering they don't use DRList.spellList.

**Comment by wardz** [comment]
Yeah, was thinking about doing something like this as a quick fix, but kinda lame that addons would have to check for the extra return values manually. If there's ever more than 2 categories they'd have to use something like `select("#", category)` to get the total count which hurts performance. (Unless second return arg is always an array only containing shared DRs, then you could just check if the array exist and use `#` operator directly. First return arg would work as normal still.)

Guess there's not much else we can do since we cant break DRData or older DRList compability either. I'll take a further look into it this weekend when i get the time.

**Comment by wardz** [comment]
Mostly completed now in v1.5.0.
